version: '3.3'

volumes:
  pg_data:
  static:
  media:

networks:
  infra_network:
    external: true

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - infra_network
    
  backend:
    build: ../backend/
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - static:/static/
      - media:/app/media
    depends_on:
      - db
    networks:
      - infra_network

  frontend:
    env_file: .env
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    networks:
      - infra_network

  nginx:
    image: nginx:1.19.3
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - static:/static/
      - media:/app/media
    depends_on:
      - frontend
      - backend
    restart: on-failure
    networks:
      - infra_network
